### ISSUE TITLE
Request for license information

### ISSUE THREAD

**Issue by lampnout** [tvgdb/cobaltstrike-cat-bof#1]
Hey!

Thanks for implementing and sharing this.

I'd like to re-use the code as part of a project I'm working on. Would it be possible to add license information?

Regards

**Comment by tvgdb** [comment]
MIT license added! 

https://github.com/tvgdb/cobaltstrike-cat-bof/blob/master/LICENSE

**Comment by lampnout** [comment]
Thank you so much!
